# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
